export type AuthErrorType = {
  type:
    | "EMAIL_INVALID"
    | "USERNAME_INVALID_LENGTH"
    | "USERNAME_CONTAINS_INVALID_CHARACTERS"
    | "PASSWORD_TOO_SHORT"
    | "PASSWORD_REQUIREMENTS_NOT_MET"
    | "USERNAME_IN_USE"
    | "EMAIL_IN_USE"
    | "TOKEN_CREATION_FAILED"
    | "USER_NOT_FOUND"
    | "NO_CREDENTIALS_PROVIDED"
    | "INVALID_LOGIN_CREDENTIALS"
    | "EMPTY_DTO_FIELD"
    | "INVALID_DTO_FIELD"
    | "EMPTY_BODY"
    | "EMPTY_USERNAME"
    | "EMPTY_EMAIL"
    | "EMPTY_DISPLAY_NAME"
    | "EMPTY_PASSWORD"
    | "TOKEN_DOES_NOT_EXIST"
    | "NO_AUTHORIZATION";
};

export type DMChannelErrorType = AuthErrorType | ServerErrorType | {
  type: "EMPTY_USERS_LIST";
};

export type ServerErrorType = {
  type: "INTERNAL_SERVER_ERROR" | "DATABASE_ERROR" | "VALIDATION_ERROR";
};
