export type AuthErrorType = {
  type:
    | "EMAIL_INVALID"
    | "USERNAME_INVALID_LENGTH"
    | "USERNAME_CONTAINS_INVALID_CHARACTERS"
    | "PASSWORD_TOO_SHORT"
    | "PASSWORD_REQUIREMENTS_NOT_MET"
    | "USERNAME_IN_USE"
    | "EMAIL_IN_USE"
    | "TOKEN_CREATION_FAILED"
    | "USER_NOT_FOUND"
};

export type ServerErrorType = {
  type: "INTERNAL_SERVER_ERROR"|"DATABASE_ERROR"|"VALIDATION_ERROR";
};